format = """
[](#294172)\
[  ](bg:#294172)\
$os\
$username\
[](bg:#3c6eb4 fg:#294172)\
$directory\
[](fg:#3c6eb4 bg:#51a2da)\
$git_branch\
$git_status\
[](fg:#51a2da bg:#a07cbc)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#a07cbc bg:#db3279)\
$docker_context\
[](fg:#db3279 bg:#294172)\
$time\
[ ](fg:#294172)\
"""

[username]
show_always = true
style_user = "bg:#294172"
style_root = "bg:#294172"
format = '[$user ]($style)'
disabled = false

[os]
style = "bg:#294172"
disabled = true

[directory]
style = "bg:#3c6eb4"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[c]
symbol = " "
style = "bg:#a07cbc"
format = '[ $symbol ($version) ]($style)'

[cpp]
symbol = " "
style = "bg:#a07cbc"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#db3279"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:#a07cbc"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#a07cbc"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#51a2da"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#51a2da"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#a07cbc"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#a07cbc"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#a07cbc"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#a07cbc"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#a07cbc"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#a07cbc"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#a07cbc"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#a07cbc"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#a07cbc"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#294172"
format = '[ ♥ $time ]($style)'
