format = """
[](#54487A)\
[ 󰣨 ](bg:#54487A)\
$os\
$username\
[](bg:#61538D fg:#54487A)\
$directory\
[](fg:#61538D bg:#6E56AF)\
$git_branch\
$git_status\
[](fg:#6E56AF bg:#54487A)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#54487A bg:#61538D)\
$docker_context\
[](fg:#61538D bg:#6E56AF)\
$time\
[ ](fg:#6E56AF)\
"""

[username]
show_always = true
style_user = "bg:#54487A"
style_root = "bg:#54487A"
format = '[$user ]($style)'
disabled = false

[os]
style = "bg:#54487A"
disabled = true

[directory]
style = "bg:#61538D"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[c]
symbol = " "
style = "bg:#54487A"
format = '[ $symbol ($version) ]($style)'

[cpp]
symbol = " "
style = "bg:#54487A"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#61538D"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:#54487A"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#54487A"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#6E56AF"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#6E56AF"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#54487A"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#54487A"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#54487A"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#54487A"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#54487A"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#54487A"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#54487A"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#54487A"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#54487A"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#6E56AF"
format = '[ ♥ $time ]($style)'
