format = """
[](#772953)\
[ 󰕈 ](bg:#772953)\
$os\
$username\
[](bg:#E95420 fg:#772953)\
$directory\
[](fg:#E95420 bg:#772953)\
$git_branch\
$git_status\
[](fg:#772953 bg:#E95420)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#E95420 bg:#772953)\
$docker_context\
[](fg:#772953 bg:#E95420)\
$time\
[ ](fg:#E95420)\
"""

[username]
show_always = true
style_user = "bg:#772953"
style_root = "bg:#772953"
format = '[$user ]($style)'
disabled = false

[os]
style = "bg:#772953"
disabled = true # Disabled by default

[directory]
style = "bg:#E95420"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[c]
symbol = " "
style = "bg:#E95420"
format = '[ $symbol ($version) ]($style)'

[cpp]
symbol = " "
style = "bg:#E95420"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#772953"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:#E95420"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#E95420"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#772953"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#772953"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#E95420"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#E95420"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#E95420"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#E95420"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#E95420"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#E95420"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#E95420"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#E95420"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#E95420"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#E95420"
format = '[ ♥ $time ]($style)'
